### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Mailaender** [sdthompson1/knights#1]
I already guessed some dependencies
* boost filesystem,system,thread (which version?)
* enet
* SDL(2?)
* Lua (5.4?) compiled with g++

currently stuck at

```
fatal error: network/byte_buf.hpp: No such file or directory
```

**Comment by sdthompson1** [comment]
Hi, first of all, please could you check the [build instructions document](https://www.knightsgame.org.uk/manual/building.html) and see if that solves your issue. It should let you know the dependencies at least.

Secondly, how are you building? Just cloning the repo and typing "make"? If so, it should be able to find all the files (I just tried exactly that on my machine and it worked). Maybe you have edited the Makefile or you are using your own build process? In which case, you need to make sure you are using the right "-I" flags, for example, you will need "-Isrc/coercri", I think, to be able to find [network/byte_buf.hpp](https://github.com/sdthompson1/knights/blob/main/src/coercri/network/byte_buf.hpp).

**Comment by Mailaender** [comment]
I am trying to build a @flatpak package. https://github.com/Mailaender/flathub/blob/knightsgame/uk.org.knightsgame.Knights.yaml
